# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    path:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    methods:  [GET]

BloggerBlogBundle_about:
    path:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    methods:  [GET]
