# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    path:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    methods:  [GET]

BloggerBlogBundle_about:
    path:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    methods:  [GET]

BloggerBlogBundle_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    methods:  [GET, POST]

BloggerBlogBundle_blog_show:
    path:  /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    methods: [GET]
    requirements:
        id: \d+