# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    methods:  [GET]

BloggerBlogBundle_about:
    path:     /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    methods:  [GET]

BloggerBlogBundle_contact:
    path:     /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    methods:  [GET, POST]

BloggerBlogBundle_blog_show:
    path:     /{id}/{slug}/{comments}
    defaults: { _controller: BloggerBlogBundle:Blog:show, comments:true }
    methods:  [GET]
    requirements:
        id:   \d+

BloggerBlogBundle_comment_create:
    path:     /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    methods:  [POST]
    requirements:
        blog_id: \d+